/** Default data when the database is empty (matches legacy SPA bootstrap). */

export const SEED_UNITS = [
  {
    id: '1',
    name: 'ICU East',
    type: 'Critical Care',
    location: 'Main Building',
    floor: '4',
    department: 'Critical Care',
    targetDecibel: 40,
    deviceName: 'SN-ICU-01',
    deviceId: 'QC-1001',
    readingSource: 'demo' as const,
    createdAt: Date.now(),
  },
  {
    id: '2',
    name: 'Maternity A',
    type: 'Inpatient',
    location: "Women's Center",
    floor: '2',
    department: 'Obstetrics',
    targetDecibel: 35,
    deviceName: 'SN-MAT-05',
    deviceId: 'QC-2005',
    readingSource: 'demo' as const,
    createdAt: Date.now(),
  },
] as const;

export const SEED_STAFF = [
  {
    id: 'admin',
    name: 'System Admin',
    role: 'Administrator',
    unitId: '1',
    status: 'active' as const,
    pincode: '0000',
    isAdmin: true,
    email: 'admin@quietcare.com',
    notificationPreferences: {
      thresholdAlerts: true,
      peakAlerts: true,
      criticalFeedback: true,
      systemAlerts: true,
    },
  },
  {
    id: 's1',
    name: 'Dr. Sarah Chen',
    role: 'Chief of Medicine',
    unitId: '1',
    status: 'active' as const,
    pincode: '1234',
    isAdmin: false,
    email: 'sarah.chen@hospital.com',
    notificationPreferences: {
      thresholdAlerts: true,
      peakAlerts: true,
      criticalFeedback: true,
      systemAlerts: false,
    },
  },
  {
    id: 's2',
    name: 'Nurse Mark',
    role: 'Nurse',
    unitId: '1',
    status: 'active' as const,
    pincode: '1111',
    isAdmin: false,
    email: 'mark.nurse@hospital.com',
    notificationPreferences: {
      thresholdAlerts: true,
      peakAlerts: false,
      criticalFeedback: true,
      systemAlerts: false,
    },
  },
  {
    id: 's3',
    name: 'Officer Jane',
    role: 'Quiet Compliance Officer',
    unitId: '2',
    status: 'active' as const,
    pincode: '2222',
    isAdmin: false,
    email: 'jane.quiet@hospital.com',
    notificationPreferences: {
      thresholdAlerts: true,
      peakAlerts: true,
      criticalFeedback: true,
      systemAlerts: true,
    },
  },
  {
    id: 's4',
    name: 'Miguel Rodriguez',
    role: 'Housekeeping',
    unitId: '1',
    status: 'active' as const,
    pincode: '3333',
    isAdmin: false,
    email: 'miguel.r@hospital.com',
    notificationPreferences: {
      thresholdAlerts: false,
      peakAlerts: false,
      criticalFeedback: false,
      systemAlerts: false,
    },
  },
  {
    id: 's5',
    name: 'Sam Wilson',
    role: 'Maintenance',
    unitId: '2',
    status: 'active' as const,
    pincode: '4444',
    isAdmin: false,
    email: 'sam.w@hospital.com',
    notificationPreferences: {
      thresholdAlerts: false,
      peakAlerts: false,
      criticalFeedback: false,
      systemAlerts: true,
    },
  },
] as const;

export const DEFAULT_SETTINGS = {
  notifications: true,
  aiFrequency: 'Every 15 Minutes',
  retention: '90 Days',
};
