import React, { useState, useEffect } from 'react';
import { X, Plus, Users, FileText, CheckCircle2, Trash2, Calendar, Download } from 'lucide-react';
import { Meeting, StaffMember } from '../types';
import { cn } from '../lib/utils';
import { jsPDF } from 'jspdf';

interface MeetingModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (meeting: Omit<Meeting, 'id' | 'timestamp'>) => void;
  staff: StaffMember[];
  initialData?: Meeting | null;
}

export const MeetingModal: React.FC<MeetingModalProps> = ({ isOpen, onClose, onSave, staff, initialData }) => {
  const [formData, setFormData] = useState({
    title: '',
    attendees: [] as string[],
    notes: '',
    decisions: [] as string[],
    nextSteps: [] as string[],
  });

  const [newDecision, setNewDecision] = useState('');
  const [newNextStep, setNewNextStep] = useState('');

  useEffect(() => {
    if (initialData) {
      setFormData({
        title: initialData.title,
        attendees: initialData.attendees,
        notes: initialData.notes,
        decisions: initialData.decisions,
        nextSteps: initialData.nextSteps,
      });
    } else {
      setFormData({
        title: '',
        attendees: [],
        notes: '',
        decisions: [],
        nextSteps: [],
      });
    }
  }, [initialData, isOpen]);

  if (!isOpen) return null;

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const blue = '#2563eb';
    const dark = '#0f172a';
    const gray = '#64748b';

    // Header
    doc.setFillColor(dark);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor('#ffffff');
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Meeting Minutes', 20, 25);
    doc.setFontSize(10);
    doc.text(`Quietness Committee • ${new Date(initialData?.timestamp || Date.now()).toLocaleDateString()}`, 20, 32);

    // Title
    doc.setTextColor(dark);
    doc.setFontSize(16);
    doc.text(formData.title || 'Untitled Meeting', 20, 55);
    
    // Attendees
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Attendees:', 20, 65);
    doc.setFont('helvetica', 'normal');
    const attendeeNames = formData.attendees
      .map(id => staff.find(s => s.id === id)?.name || 'Unknown')
      .join(', ');
    const splitAttendees = doc.splitTextToSize(attendeeNames || 'None listed', 170);
    doc.text(splitAttendees, 20, 70);

    let y = 70 + (splitAttendees.length * 5) + 10;

    // Notes
    doc.setFont('helvetica', 'bold');
    doc.text('Discussion & Notes:', 20, y);
    doc.setFont('helvetica', 'normal');
    const splitNotes = doc.splitTextToSize(formData.notes || 'No notes recorded.', 170);
    doc.text(splitNotes, 20, y + 5);
    
    y += (splitNotes.length * 5) + 15;

    // Decisions
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(blue);
    doc.text('Key Decisions:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(dark);
    formData.decisions.forEach((decision, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`• ${decision}`, 25, y + 7 + (i * 6));
    });
    
    y += (formData.decisions.length * 6) + 15;

    // Next Steps
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(blue);
    doc.text('Next Steps:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(dark);
    formData.nextSteps.forEach((step, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`${i + 1}. ${step}`, 25, y + 7 + (i * 6));
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(gray);
    doc.text('Generated by QuietCare Acoustic Intelligence System • Medamaitrak.com', 20, 285);

    doc.save(`Meeting_Minutes_${formData.title.replace(/\s+/g, '_') || 'Quietness'}.pdf`);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
    onClose();
  };

  const toggleAttendee = (staffId: string) => {
    setFormData(prev => ({
      ...prev,
      attendees: prev.attendees.includes(staffId)
        ? prev.attendees.filter(id => id !== staffId)
        : [...prev.attendees, staffId]
    }));
  };

  const addDecision = () => {
    if (newDecision.trim()) {
      setFormData(prev => ({
        ...prev,
        decisions: [...prev.decisions, newDecision.trim()]
      }));
      setNewDecision('');
    }
  };

  const removeDecision = (index: number) => {
    setFormData(prev => ({
      ...prev,
      decisions: prev.decisions.filter((_, i) => i !== index)
    }));
  };

  const addNextStep = () => {
    if (newNextStep.trim()) {
      setFormData(prev => ({
        ...prev,
        nextSteps: [...prev.nextSteps, newNextStep.trim()]
      }));
      setNewNextStep('');
    }
  };

  const removeNextStep = (index: number) => {
    setFormData(prev => ({
      ...prev,
      nextSteps: prev.nextSteps.filter((_, i) => i !== index)
    }));
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-md">
      <div className="bg-white rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200 flex flex-col max-h-[90vh]">
        <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-100 rounded-lg">
              <Users className="w-5 h-5 text-blue-600" />
            </div>
            <h2 className="text-xl font-bold text-slate-900 tracking-tight">
              {initialData ? 'Review Meeting' : 'Conduct Quietness Committee Meeting'}
            </h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-200 rounded-full transition-colors">
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto p-8 space-y-8 custom-scrollbar">
          <div className="space-y-6">
            {/* Title */}
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1.5">Meeting Title</label>
              <div className="relative">
                <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input
                  required
                  type="text"
                  placeholder="e.g. Monthly Quietness Review - March 2026"
                  className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all text-sm"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                />
              </div>
            </div>

            {/* Attendees */}
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1.5">Attendees</label>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                {staff.map(member => (
                  <button
                    key={member.id}
                    type="button"
                    onClick={() => toggleAttendee(member.id)}
                    className={cn(
                      "flex items-center gap-2 px-3 py-2 rounded-lg border text-xs font-medium transition-all text-left",
                      formData.attendees.includes(member.id)
                        ? "bg-blue-50 border-blue-200 text-blue-700 shadow-sm"
                        : "bg-white border-slate-200 text-slate-600 hover:border-slate-300"
                    )}
                  >
                    <div className={cn(
                      "w-2 h-2 rounded-full",
                      formData.attendees.includes(member.id) ? "bg-blue-500" : "bg-slate-300"
                    )} />
                    <span className="truncate">{member.name}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Notes */}
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1.5">Meeting Notes</label>
              <div className="relative">
                <FileText className="absolute left-3 top-4 w-4 h-4 text-slate-400" />
                <textarea
                  required
                  placeholder="Document the discussion, acoustic trends, and staff feedback..."
                  className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all text-sm min-h-[120px]"
                  value={formData.notes}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                />
              </div>
            </div>

            {/* Decisions */}
            <div className="space-y-3">
              <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1.5">Key Decisions</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder="Add a decision..."
                  className="flex-1 px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-sm"
                  value={newDecision}
                  onChange={(e) => setNewDecision(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addDecision())}
                />
                <button
                  type="button"
                  onClick={addDecision}
                  className="p-2 bg-slate-900 text-white rounded-xl hover:bg-slate-800 transition-colors"
                >
                  <Plus className="w-5 h-5" />
                </button>
              </div>
              <div className="space-y-2">
                {formData.decisions.map((decision, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border border-slate-100 group">
                    <div className="flex items-center gap-3">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                      <span className="text-sm text-slate-700">{decision}</span>
                    </div>
                    <button
                      type="button"
                      onClick={() => removeDecision(index)}
                      className="p-1 hover:bg-red-50 text-slate-400 hover:text-red-500 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* Next Steps */}
            <div className="space-y-3">
              <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1.5">Next Steps</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  placeholder="Add a next step..."
                  className="flex-1 px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-sm"
                  value={newNextStep}
                  onChange={(e) => setNewNextStep(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), addNextStep())}
                />
                <button
                  type="button"
                  onClick={addNextStep}
                  className="p-2 bg-slate-900 text-white rounded-xl hover:bg-slate-800 transition-colors"
                >
                  <Plus className="w-5 h-5" />
                </button>
              </div>
              <div className="space-y-2">
                {formData.nextSteps.map((step, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-slate-50 rounded-xl border border-slate-100 group">
                    <div className="flex items-center gap-3">
                      <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                      <span className="text-sm text-slate-700">{step}</span>
                    </div>
                    <button
                      type="button"
                      onClick={() => removeNextStep(index)}
                      className="p-1 hover:bg-red-50 text-slate-400 hover:text-red-500 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </form>

        <div className="p-6 border-t border-slate-100 bg-slate-50 flex flex-wrap gap-3">
          <button
            type="button"
            onClick={onClose}
            className="flex-1 py-3 border border-slate-200 text-slate-600 rounded-xl font-bold text-xs uppercase tracking-widest hover:bg-white transition-all"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleDownloadPDF}
            className="flex-1 py-3 bg-slate-100 text-slate-600 rounded-xl font-bold text-xs uppercase tracking-widest hover:bg-slate-200 transition-all flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download Minutes
          </button>
          <button
            onClick={handleSubmit}
            className="flex-[2] py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-xl font-bold text-xs uppercase tracking-widest shadow-lg shadow-blue-100 transition-all flex items-center justify-center gap-2"
          >
            <CheckCircle2 className="w-4 h-4" />
            {initialData ? 'Update Minutes' : 'Save Meeting Minutes'}
          </button>
        </div>
      </div>
    </div>
  );
};
